import { Inter } from 'next/font/google'
import './globals.css'
import ToastComponent from '@/components/ToastComponent'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'next_crypto',
  description: 'Generated by Rajat R1152',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastComponent />
        {children}
      </body>
    </html>
  )
}
